version: "2.2"
services:

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: cicd-jenkins
    restart: unless-stopped
    networks:
      - jenkins
    ports:
      - "50000:50000"
    environment:
      # Uncomment JENKINS_OPTS to add prefix: e.g. https://127.0.0.1:8443/jenkins
      #- JENKINS_OPTS="--prefix=/jenkins"
      - JENKINS_UID=${JENKINS_UID}
      - JENKINS_GID=${JENKINS_GID}
    volumes:
      - ${JENKINS_LOCAL_HOME}:/var/jenkins_home
      - ${HOST_DOCKER_SOCK}:/var/run/docker.sock

  sonarqube:
          image: sonarqube:8.9-community
    container_name: cicd-sonarqube
    restart: unless-stopped
    networks:
      - jenkins
    ports:
      - "9000:9000"    # http
    volumes:
      - ${SONARQUBE_CONF}:/opt/sonarqube/conf
      - ${SONARQUBE_DATA}:/opt/sonarqube/data
      - ${SONARQUBE_EXTENSIONS}:/opt/sunarqube/extensions
      - ${SONARQUBE_BUNDLED-PLUGINS}:/opt/sonarqube/lib/bundled-plugins
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar

networks:
  jenkins:
    name: cicd-jenkins
    driver: bridge
